version : '2'
services:
  postgres:
    image: 'postgres:latest'
    restart: always
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
    
    environment:
      - POSTGRES_PASSWORD=secret123!
    ports:
      - '5432:5432'
  
  nest: 
    image: 'manuminnig/nest'
    ports: 
      - '3000:3000'
   
    environment:
      - DATABASE_NAME=postgres
      - DATABASE_HOST=postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=secret123!
      - DATABASE_PORT=5432

  angular: 
    build: .
    ports: 
      - '4200:4200'

volumes:
  postgres_data:
