apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-deployment
  labels:
    app: angular
spec:
  replicas: 3
  selector:
    matchLabels:
      app: angular
  template:
    metadata:
      labels:
        app: angular
    spec:
      containers:
      - name: api
        image: manuminnig/angular:test-env
        env:
          - name: API_URL
            value: HOLAMUNDO
        ports:
        - containerPort: 4200